# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "carrot"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Amos Elliston"]
  s.date = "2011-10-07"
  s.description = "A synchronous version of the ruby amqp client"
  s.email = "amos@geni.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION.yml",
    "carrot.gemspec",
    "lib/carrot.rb",
    "lib/carrot/amqp/buffer.rb",
    "lib/carrot/amqp/exchange.rb",
    "lib/carrot/amqp/frame.rb",
    "lib/carrot/amqp/header.rb",
    "lib/carrot/amqp/protocol.rb",
    "lib/carrot/amqp/queue.rb",
    "lib/carrot/amqp/server.rb",
    "lib/carrot/amqp/spec.rb",
    "lib/examples/simple_pop.rb",
    "protocol/amqp-0.8.json",
    "protocol/amqp-0.8.xml",
    "protocol/codegen.rb",
    "protocol/doc.txt",
    "test/buffer_test.rb",
    "test/carrot_test.rb",
    "test/frame_test.rb",
    "test/protocol_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/famoseagle/carrot"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "A synchronous version of the ruby amqp client"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<mocha>, [">= 0"])
    else
      s.add_dependency(%q<mocha>, [">= 0"])
    end
  else
    s.add_dependency(%q<mocha>, [">= 0"])
  end
end

